# Generated by Django 3.1.2 on 2020-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201229_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='imagen',
            field=models.URLField(default=None, null=True, verbose_name='Imagen'),
        ),
    ]
